"""Tool registry — the only way Labwright's agent reaches the calculators.

The registry is deliberately tiny. A :class:`Tool` binds three things:

- a ``pydantic`` parameter model (validates input and produces the JSON Schema
  the LLM needs for tool calling),
- a pure function from :mod:`labwright.calc` (the actual math),
- prose that tells the LLM when to call it.

**Extending Labwright** (this is the documented extension point): write a
calculator in :mod:`labwright.calc`, then add a ``Tool`` here. Nothing else
needs to change. The agent, the verifier and the demo all read the same
registry, so a new calculator is instantly callable, verifiable and
demonstrable.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable

from pydantic import BaseModel, Field

from labwright.calc import barrier, bioinformatics, bioprinting, cell, coculture, culture, dosing, enzyme, microfluidics as mf, o2, pk, solvent, spheroid, stats
from labwright.published import verify_published_protocol

# ---------------------------------------------------------------------------
# Registry primitives
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Tool:
    """A callable calculator exposed to the agent."""

    name: str
    description: str
    params_model: type[BaseModel]
    func: Callable[..., Any]
    category: str
    units_out: str = ""

    @property
    def schema(self) -> dict[str, Any]:
        """OpenAI-style function-tool schema for this tool.

        The description sent to the model is the tool's prose plus a concrete
        worked example and the most common unit/input error (from
        ``_TOOL_NOTES``), so the model learns how to call the tool correctly
        rather than by trial and error.
        """
        description = self.description
        note = _TOOL_NOTES.get(self.name)
        if note is not None:
            example, watch = note
            if example:
                description += f"  Example: {example}"
            if watch:
                description += f"  Watch out: {watch}"
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": description,
                "parameters": self.params_model.model_json_schema(),
            },
        }

    def call(self, **kwargs: Any) -> Any:
        """Validate arguments against the model, then run the calculator."""
        return self.func(**self.params_model(**kwargs).model_dump())


REGISTRY: dict[str, Tool] = {}

#: Worked example + most common error per tool, appended to the description the
#: model sees. Examples are real outputs (generated by the calculators); the
#: "watch out" hints target the unit/scale mistakes the benchmark actually sees.
_TOOL_NOTES: dict[str, tuple[str, str]] = {
    "wall_shear_stress": (
        "wall_shear_stress(10, 400, 100, 0.001) -> 0.25 Pa",
        "flow is per channel in µL/min and geometry in µm — a mL/min flow or mm "
        "geometry gives a ~1000× error; a dyn/cm² answer is 10× the Pa value",
    ),
    "flow_rate_for_shear_stress": (
        "flow_rate_for_shear_stress(0.05, 400, 100, 0.001) -> 2.0 µL/min",
        "the target shear is in Pa; convert a dyn/cm² target to Pa first (×0.1)",
    ),
    "reynolds_number": (
        "reynolds_number(10, 400, 100, 0.001, 1000) -> 0.67",
        "microfluidic flows are laminar; Re > 2300 means the channel is not OOC",
    ),
    "pressure_drop": (
        "pressure_drop(10, 400, 100, 20, 0.001) -> 100 Pa",
        "length is in mm, not µm; a common 1000× mistake",
    ),
    "residence_time": (
        "residence_time(10, 400, 100, 20) -> 4.8 s",
        "geometry in µm/mm; mixing units gives a wrong volume",
    ),
    "o2_delivery_rate": (
        "o2_delivery_rate(10, 0.0002) -> 0.002 µmol/min",
        "C_in is in mol/L (0.2e-3 for air-equilibrated medium), not mM",
    ),
    "seeding_cell_count": (
        "seeding_cell_count(5e4, 0.08) -> 4000 cells",
        "density in cells/cm² × area in cm²; a mm² area is 100× too small",
    ),
    "cell_count_after_time": (
        "cell_count_after_time(8000, 30, 72) -> ~4.2e4 cells",
        "doubling time and elapsed both in hours",
    ),
    "time_to_confluence": (
        "time_to_confluence(8000, 8e4, 30) -> ~100 h",
        "confluence_count is the cell count at the target confluence",
    ),
    "cells_per_well": (
        "cells_per_well(1e4, '96') -> 3200 cells/well",
        "plate_format is the well count ('96'), not a float",
    ),
    "medium_volume_per_well": (
        "medium_volume_per_well('96') -> 0.17 mL",
        "returns the standard working volume for the format",
    ),
    "hemocytometer_count": (
        "hemocytometer_count(32, 2) -> 6.4e5 cells/mL",
        "avg per 1 mm² square × dilution × 1e4 (each square holds 0.1 µL)",
    ),
    "trypan_blue_viability": (
        "trypan_blue_viability(90, 10) -> 90%",
        "live/(live+dead), not dead/live",
    ),
    "confluence_to_cell_count": (
        "confluence_to_cell_count(50, 1e6, 0.32) -> 1.6e5 cells",
        "confluent density is the 100% value for the cell type",
    ),
    "cell_count_to_confluence": (
        "cell_count_to_confluence(1.6e5, 1e6, 0.32) -> 50%",
        "can exceed 100 for an over-confluent harvest",
    ),
    "passage_split_ratio": (
        "passage_split_ratio(1.6e6, 5e4, '24') -> ~17-fold",
        "harvested cells ÷ (reseeding density × well area)",
    ),
    "moi_virus_volume": (
        "moi_virus_volume(1, 1e5, 1e8) -> 0.001 mL",
        "titer in PFU/mL; volume = MOI × cells / titer",
    ),
    "molarity_from_mass": (
        "molarity_from_mass(5, 151.16, 50) -> ~0.66 mM",
        "mass in mg, MW in g/mol, volume in mL",
    ),
    "dilution_volume": (
        "dilution_volume(100, 0.5, 5) -> 0.025 mL",
        "target_mM must be < stock_mM",
    ),
    "dmso_fraction": (
        "dmso_fraction(100, 0.1) -> 0.001 (0.1% v/v)",
        "keep ≤ 0.5% v/v — higher is cytotoxic for most cells",
    ),
    "sample_size_per_group": (
        "sample_size_per_group(1.0, 1.0, 0.05, 0.8) -> 16 per group",
        "effect_size and std_dev in the same units; power defaults 0.8",
    ),
    "technical_replicates": (
        "technical_replicates(10, 5, 0.05) -> 16",
        "cv and precision in percent",
    ),
    "verify_published_protocol": (
        "verify_published_protocol({chip: {...}, flow: {...}, claimed: {'shear_pa': 0.05}, reference: 'DOI'}) "
        "-> per-field verdict",
        "claimed values that do not follow from the paper's own inputs are flagged",
    ),
    "spheroid_volume": (
        "spheroid_volume(200) -> 0.004189 µL",
        "diameter in µm; volume comes out in µL (1000 µm³ = 1 nL)",
    ),
    "spheroid_diameter_from_cells": (
        "spheroid_diameter_from_cells(1000, 20) -> ~200 µm",
        "cell diameter in µm; 1000 cells of 20 µm ≈ a 200 µm spheroid at solid packing "
        "(packing_fraction 1.0). Real aggregates pack looser — pass packing_fraction ≈ 0.7 "
        "for a realistic estimate (~222 µm).",
    ),
    "cells_per_spheroid_for_diameter": (
        "cells_per_spheroid_for_diameter(200, 20) -> ~1000",
        "target diameter in µm; keep ≤ ~200 µm to avoid necrotic cores (oxygen diffuses ~200 µm). "
        "packing_fraction < 1 (real aggregates ≈ 0.65-0.75) needs fewer cells per spheroid.",
    ),
    "medium_volume_per_spheroid": (
        "medium_volume_per_spheroid('96-ula') -> 100 µL",
        "format is 96-ula / 384-ula / hanging-drop; volume per spheroid (one spheroid per well/drop)",
    ),
    "spheroids_from_suspension": (
        "spheroids_from_suspension(2.4e5, 1000) -> 240",
        "total cells ÷ cells per spheroid, floored",
    ),
    "cell_physiology": (
        "cell_physiology('HepG2') -> {organ: liver, doubling 48-60 h, shear 0.05-0.15 Pa, ...}",
        "literature-based reference ranges (with sources); call before choosing a physiological "
        "target rather than guessing, and never pass a registry range off as your own measurement",
    ),
    "o2_penetration_depth": (
        "o2_penetration_depth(0.1) -> ~89 µm",
        "consumption is mol/m³/s — pass volumetric_o2_consumption(cell OCR fmol/s × density) "
        "rather than a raw OCR; dense tissue ≈ 0.1 mol/m³/s → tens of µm",
    ),
    "spheroid_necrotic_fraction": (
        "spheroid_necrotic_fraction(500, 200) -> 0.008 (0.8%)",
        "penetration deeper than the radius (diameter/2) returns 0 — a 200 µm spheroid with "
        "200 µm penetration is fully oxygenated; compare the SAME units (µm)",
    ),
    "o2_supply_vs_demand": (
        "o2_supply_vs_demand(50, 1e6, 0.03) -> {ratio: 5.56, hypoxic: False}",
        "per_cell_fmol_s is the registry OCR ÷ 60 (nmol/min/1e6 cells ÷ 60); supply assumes "
        "maximal extraction, so ratio < 1 is unambiguously hypoxic",
    ),
    "o2_peclet": (
        "o2_peclet(0.5, 20) -> 5000",
        "velocity in mm/s, length in mm; Pe ≪ 1 well mixed, Pe ≫ 1 flow sweeps O2 past the cells",
    ),
    "o2_damkohler": (
        "o2_damkohler(0.1, 20, 0.5) -> 20",
        "Da > 1 means outlet O2 is depleted — downstream cells hypoxic",
    ),
    "o2_po2_conversion": (
        "o2_po2_conversion(po2_mmHg=150) -> {conc_mM: 0.201}",
        "pass exactly one of po2_mmHg or conc_mM; 150 mmHg ≈ 0.2 mM (air-equilibrated medium)",
    ),
    "teer_from_resistance": (
        "teer_from_resistance(300, 100, 1.12) -> 224 Ω·cm²",
        "must subtract the blank and multiply by area — a bare (R_total − R_blank) without "
        "× area is not a TEER; kΩ readings must be converted to Ω first",
    ),
    "transendothelial_resistance": (
        "transendothelial_resistance(224, 1.12) -> 200 Ω",
        "target TEER ÷ area; if this R is below the blank, the TEER target is unreachable "
        "on that insert size",
    ),
    "papp_from_flux": (
        "papp_from_flux(0.006, 1, 100) -> 1e-6 cm/s",
        "flux in nmol/min (÷60 → nmol/s), donor in µM (= nmol/cm³); a tight barrier is "
        "~1e-7-1e-6 cm/s, leaky ~1e-5",
    ),
    "flux_from_papp": (
        "flux_from_papp(1e-6, 100, 1.12) -> ~6.7e-3 nmol/min",
        "a low-Papp probe across a small insert is pmol/min — check the assay can resolve "
        "the flux before designing the transport study",
    ),
    "clearance_from_papp": (
        "clearance_from_papp(1e-6, 1.12) -> 6.7e-5 mL/min",
        "Papp × area × 60 (cm³/s → mL/min); clearer than bare Papp when comparing inserts",
    ),
    "effective_permeability": (
        "effective_permeability(1e-13, 20) -> 5e-7 cm/s",
        "diffusivity in m²/s, thickness in µm; this is the purely-diffusive reference — a "
        "monolayer Papp far above its passive-membrane P means active/paracellular transport",
    ),
    "extraction_ratio": (
        "extraction_ratio(10, 7) -> 0.3",
        "E = 1 − C_out/C_in, both concentrations in the SAME units (µM); a negative E means the "
        "outlet exceeds the inlet — active secretion or a measurement error, not a clamp",
    ),
    "clearance_uLmin": (
        "clearance_uLmin(10, 7, 2) -> 0.6 µL/min",
        "Cl = E·Q; flow in µL/min gives clearance in µL/min — a mL/min flow is 1000× too large",
    ),
    "half_life_h": (
        "half_life_h(200, 0.6) -> 3.85 h",
        "t½ = ln2·V/Cl; V in µL, Cl in µL/min, result in hours (the min→h ÷60 is automatic)",
    ),
    "accumulation_ratio": (
        "accumulation_ratio(3.85, 24) -> 1.06",
        "R = 1/(1 − e^(−ln2·τ/t½)); R ≥ 1 — R≈1 means no accumulation (interval ≫ half-life), "
        "R grows as τ drops below t½",
    ),
    "mass_cleared_ug_h": (
        "mass_cleared_ug_h(0.6, 10, 464) -> 1.67 µg/h",
        "M = Cl·C_in·MW·6e-5; C_in in µM (not mM — 1000× error), MW in g/mol, result in µg/h",
    ),
    "bioprinting_extrusion_volume_nl": (
        "bioprinting_extrusion_volume_nl(10000, 500) -> 1963.5 nL",
        "travel in µm, nozzle diameter in µm; a 10 mm move is 10000 µm — mixing mm gives a 1000× error",
    ),
    "bioprinting_path_length": (
        "bioprinting_path_length(8000, 6000, 0) -> 10000 µm",
        "offsets are the coordinate displacement the G-code actually encodes (Pythagoras)",
    ),
    "bioprinting_print_time": (
        "bioprinting_print_time(10000, 5) -> 120 s",
        "distance in µm, feed rate in mm/min; the mm conversion is automatic",
    ),
    "bioprinting_lines_to_cover": (
        "bioprinting_lines_to_cover(2000, 400) -> 5",
        "pitch is centre-to-centre spacing in µm, same unit as the footprint width",
    ),
    "coculture_cells_per_well": (
        "coculture_cells_per_well(5e4, 0.32, 0.25) -> (4000, 12000) cells/well",
        "fraction_a is the A share (0–1), not a percent — 25% is 0.25",
    ),
    "coculture_seeding_ratio": (
        "coculture_seeding_ratio(4000, 12000) -> 0.333",
        "returns A/B; invert (B/A) if the protocol quotes the other order",
    ),
    "enzyme_fractional_activity": (
        "enzyme_fractional_activity(180, 180, 25, 60) -> 0.227",
        "all four concentrations in the same unit (µM); ki is the inhibitor constant",
    ),
    "enzyme_ic50_from_ki": (
        "enzyme_ic50_from_ki(180, 180, 25) -> 50 µM",
        "run-condition IC50 (Cheng–Prusoff); Ki without the 1+[S]/Km factor is the intrinsic value",
    ),
    "enzyme_apparent_km": (
        "enzyme_apparent_km(180, 60, 25) -> 612 µM",
        "apparent Km rises with [I]/Ki — the catalytic Km is unchanged",
    ),
    "enzyme_molar_ratio": (
        "enzyme_molar_ratio(60, 180) -> 0.333",
        "amounts in the same molar unit; this is the [I]/[S] ratio for a competitive inhibitor",
    ),
    "champ_chips_for_samples": (
        "champ_chips_for_samples(98, '450k') -> 9 chips",
        "450k holds 12 arrays/chip, EPIC holds 8; n_chips = ceil(n_samples/capacity)",
    ),
    "champ_expected_failed_arrays": (
        "champ_expected_failed_arrays(98, 0.05) -> 4.9 arrays",
        "fail_rate is a fraction (5% = 0.05), not a percent",
    ),
    "plink_bed_size_mb": (
        "plink_bed_size_mb(800, 2400000) -> 480 MB",
        "binary .bed packs 2 bits/sample/variant — divide by 4 samples/byte then by 1e6 for MB",
    ),
    "plink_per_chr_bed_size_mb": (
        "plink_per_chr_bed_size_mb(800, 120000) -> 24 MB",
        "same 2-bits rule applied to one chromosome's variant count",
    ),
    "solvent_evaporation_rate": (
        "solvent_evaporation_rate(2, 'A', 1, 25, 0.6) -> ~11.7 µL/hr",
        "edge wells (rows A/H, cols 1/12) multiply the interior Langmuir rate by ~1.5",
    ),
    "solvent_drop_volume_after_time": (
        "solvent_drop_volume_after_time(2, 0.2, 25, 0.6, 1.5) -> ~1.14 µL",
        "the d²-law slows as the drop shrinks; a 2 µL drop at 25 °C/60% RH dries in ~23 min",
    ),
    "solvent_edge_well_factor": (
        "solvent_edge_well_factor('D', 6) -> 1.0, ('A', 1) -> 1.5",
        "only rows A/H and columns 1/12 are edge wells (documented 1.4–2.0 range)",
    ),
}


def register_tool(cls: type[BaseModel], name: str, description: str, func: Callable, category: str, units_out: str = ""):
    """Declare a tool in the global registry."""
    t = Tool(name=name, description=description, params_model=cls, func=func, category=category, units_out=units_out)
    REGISTRY[name] = t
    return t


# ---------------------------------------------------------------------------
# Parameter models
# ---------------------------------------------------------------------------


class ShearStressParams(BaseModel):
    flow_rate_uLmin: float = Field(gt=0, description="Volumetric flow rate in µL/min")
    width_um: float = Field(gt=0, description="Channel width in micrometres")
    height_um: float = Field(gt=0, description="Channel height in micrometres")
    viscosity_pas: float = Field(gt=0, description="Dynamic viscosity in Pa·s (water ≈ 1e-3, culture medium ≈ 0.9-1.1e-3)")


class FlowForShearParams(BaseModel):
    target_shear_pa: float = Field(gt=0, description="Target wall shear stress in Pa (physiological microvascular ≈ 0.01-0.1 Pa)")
    width_um: float = Field(gt=0, description="Channel width in micrometres")
    height_um: float = Field(gt=0, description="Channel height in micrometres")
    viscosity_pas: float = Field(gt=0, description="Dynamic viscosity in Pa·s")


class ReynoldsParams(BaseModel):
    flow_rate_uLmin: float = Field(gt=0, description="Volumetric flow rate in µL/min")
    width_um: float = Field(gt=0, description="Channel width in micrometres")
    height_um: float = Field(gt=0, description="Channel height in micrometres")
    viscosity_pas: float = Field(gt=0, description="Dynamic viscosity in Pa·s")


class PressureDropParams(BaseModel):
    flow_rate_uLmin: float = Field(gt=0, description="Volumetric flow rate in µL/min")
    width_um: float = Field(gt=0, description="Channel width in micrometres")
    height_um: float = Field(gt=0, description="Channel height in micrometres")
    length_mm: float = Field(gt=0, description="Channel length in millimetres")
    viscosity_pas: float = Field(gt=0, description="Dynamic viscosity in Pa·s")


class ResidenceTimeParams(BaseModel):
    flow_rate_uLmin: float = Field(gt=0, description="Volumetric flow rate in µL/min")
    width_um: float = Field(gt=0, description="Channel width in micrometres")
    height_um: float = Field(gt=0, description="Channel height in micrometres")
    length_mm: float = Field(gt=0, description="Channel length in millimetres")


class O2DeliveryParams(BaseModel):
    flow_rate_uLmin: float = Field(gt=0, description="Volumetric flow rate in µL/min")
    o2_in_mol_L: float = Field(gt=0, description="Dissolved O2 concentration entering channel in mol/L (air-equilibrated ≈ 0.2e-3)")
    o2_out_mol_L: float = Field(ge=0, default=0.0, description="Dissolved O2 leaving channel in mol/L")


class SeedCountParams(BaseModel):
    density_cells_cm2: float = Field(gt=0, description="Seeding density in cells/cm^2 (HepG2 ≈ 5e4-1e5, primary hepatocytes ≈ 1e5)")
    area_cm2: float = Field(gt=0, description="Culture area in cm^2 (a 400 µm × 20 mm × 100 µm channel ≈ 0.08 cm^2)")


class GrowthParams(BaseModel):
    seed_count: float = Field(gt=0, description="Cells seeded at t=0")
    doubling_time_h: float = Field(gt=0, description="Population doubling time in hours (HepG2 ≈ 30-40 h)")
    elapsed_h: float = Field(ge=0, description="Elapsed time in hours")


class ConfluenceTimeParams(BaseModel):
    seed_count: float = Field(gt=0, description="Seeded cell count")
    confluence_count: float = Field(gt=0, description="Cell count at desired confluence")
    doubling_time_h: float = Field(gt=0, description="Doubling time in hours")


class PlateCellPerWellParams(BaseModel):
    seed_density_cells_cm2: float = Field(gt=0, description="Seeding density in cells/cm^2 (HepG2 growth-phase 2e4-6.3e4, primary hepatocyte sandwich 1.5e5)")
    plate_format: str = Field(description="Plate format: 6, 12, 24, 48 or 96 (e.g. '96-well')")


class PlateMediumVolumeParams(BaseModel):
    plate_format: str = Field(description="Plate format: 6, 12, 24, 48 or 96")
    volume_per_area_ml_cm2: float | None = Field(
        default=None, gt=0,
        description="Optional override: mL of medium per cm^2 of growth area (for shallow-well / low-volume protocols)",
    )


class HemocytometerParams(BaseModel):
    avg_cells_per_square: float = Field(gt=0, description="Mean cells per 1 mm^2 corner square of the hemocytometer")
    dilution_factor: float = Field(ge=1, description="Sample dilution factor (1 = neat)")


class TrypanViabilityParams(BaseModel):
    live_cells: float = Field(ge=0, description="Live (unstained) cell count")
    dead_cells: float = Field(ge=0, description="Dead (blue-stained) cell count")


class ConfluenceToCellsParams(BaseModel):
    confluence_pct: float = Field(gt=0, le=100, description="Target confluence in percent")
    confluent_density_cells_cm2: float = Field(gt=0, description="Cells/cm^2 at 100% confluence for this cell type")
    area_cm2: float = Field(gt=0, description="Culture area in cm^2")


class CellsToConfluenceParams(BaseModel):
    cell_count: float = Field(gt=0, description="Observed/predicted cell count")
    confluent_density_cells_cm2: float = Field(gt=0, description="Cells/cm^2 at 100% confluence for this cell type")
    area_cm2: float = Field(gt=0, description="Culture area in cm^2")


class PassageSplitParams(BaseModel):
    cells_at_harvest: float = Field(gt=0, description="Cells harvested per well at passage")
    seed_density_cells_cm2: float = Field(gt=0, description="Reseeding density in cells/cm^2")
    plate_format: str = Field(description="Plate format for reseeding (6/12/24/48/96)")


class MoiVirusParams(BaseModel):
    moi: float = Field(gt=0, description="Multiplicity of infection (PFU/cell)")
    cell_count: float = Field(gt=0, description="Cells at infection")
    titer_pfu_ml: float = Field(gt=0, description="Virus titer in PFU/mL")


class MolarityParams(BaseModel):
    mass_mg: float = Field(gt=0, description="Mass of compound in mg")
    molecular_weight_g_mol: float = Field(gt=0, description="Molecular weight in g/mol")
    volume_ml: float = Field(gt=0, description="Final volume in mL")


class DilutionParams(BaseModel):
    stock_mM: float = Field(gt=0, description="Stock concentration in mM")
    target_mM: float = Field(gt=0, description="Desired working concentration in mM")
    target_volume_ml: float = Field(gt=0, description="Final working volume in mL")


class DmsoParams(BaseModel):
    stock_dmso_mM: float = Field(gt=0, description="Compound concentration in pure DMSO stock, mM")
    working_mM: float = Field(gt=0, description="Desired working concentration in medium, mM")


class SampleSizeParams(BaseModel):
    effect_size: float = Field(gt=0, description="Expected difference between group means (measurement units)")
    std_dev: float = Field(gt=0, description="Expected pooled standard deviation (same units as effect_size)")
    alpha: float = Field(default=0.05, gt=0, lt=1, description="Type-I error rate")
    power: float = Field(default=0.80, gt=0, lt=1, description="Target statistical power")
    two_sided: bool = Field(default=True, description="Two-sided test (recommended)")


class ReplicatesParams(BaseModel):
    cv_pct: float = Field(gt=0, description="Assay coefficient of variation in percent")
    precision_pct: float = Field(gt=0, description="Desired relative precision (95% CI half-width) in percent")
    alpha: float = Field(default=0.05, gt=0, lt=1, description="Confidence level")


class ChipClaimParams(BaseModel):
    width_um: float = Field(gt=0, description="Channel width in micrometres, as reported")
    height_um: float = Field(gt=0, description="Channel height in micrometres, as reported")
    length_mm: float = Field(gt=0, description="Channel length in millimetres, as reported")


class FlowClaimParams(BaseModel):
    flow_rate_uLmin: float = Field(gt=0, description="Volumetric flow rate in µL/min, as reported")
    viscosity_pas: float = Field(default=1e-3, gt=0, description="Dynamic viscosity in Pa·s")
    density_kgm3: float = Field(default=1000, gt=0, description="Fluid density in kg/m³")


class VerifyProtocolParams(BaseModel):
    chip: ChipClaimParams = Field(description="Channel geometry the paper reports")
    flow: FlowClaimParams = Field(description="Flow inputs the paper reports")
    claimed: dict[str, float] = Field(
        description='Derived values the paper asserts, e.g. {"shear_pa": 0.05, "reynolds": 0.3, '
        '"channel_volume_ul": 0.8}'
    )
    reference: str = Field(description="DOI / journal citation of the paper being checked (required)")


class SpheroidVolumeParams(BaseModel):
    diameter_um: float = Field(gt=0, description="Spheroid diameter in micrometres")


class SpheroidDiameterFromCellsParams(BaseModel):
    cells_per_spheroid: float = Field(gt=0, description="Cells seeded per spheroid")
    cell_diameter_um: float = Field(gt=0, description="Mean single-cell diameter in micrometres (hepatocytes ≈ 20)")
    packing_fraction: float = Field(
        default=1.0, gt=0, le=1,
        description="Volume fraction of the spheroid occupied by cells (0-1). 1.0 = solid-sphere "
        "packing (the convention behind '1000 cells ≈ 200 µm'); real aggregates pack looser, "
        "~0.65-0.75 — pass e.g. 0.74 for a realistic size estimate.",
    )


class CellsPerSpheroidParams(BaseModel):
    target_diameter_um: float = Field(gt=0, description="Target spheroid diameter in micrometres")
    cell_diameter_um: float = Field(gt=0, description="Mean single-cell diameter in micrometres")
    packing_fraction: float = Field(
        default=1.0, gt=0, le=1,
        description="Volume fraction of the spheroid occupied by cells (0-1). 1.0 = solid-sphere "
        "packing; real aggregates pack looser, ~0.65-0.75 — fewer cells are needed at lower packing.",
    )


class MediumPerSpheroidParams(BaseModel):
    spheroid_format: str = Field(description="Vessel/format: 96-ula / 384-ula / hanging-drop")


class SpheroidCountParams(BaseModel):
    total_cells: float = Field(gt=0, description="Total viable cells in the suspension")
    cells_per_spheroid: float = Field(gt=0, description="Cells per spheroid")


class CellPhysiologyParams(BaseModel):
    cell_type: str = Field(
        description="Cell type or line to look up, e.g. 'HepG2', 'primary human "
        "hepatocytes', 'Caco-2', 'HUVEC' — fuzzy matching, names are normalized"
    )


class O2PenetrationParams(BaseModel):
    volumetric_consumption_mol_m3s: float = Field(
        gt=0,
        description="Volumetric O2 consumption in mol/m³/s. Estimate as "
        "per-cell rate (fmol/s) × cell density (cells/mL): hepatocytes ≈ "
        "0.007-0.08 fmol/s/cell; a 200 µm spheroid ≈ 2.4e11 cells/mL.",
    )
    surface_conc_mM: float = Field(default=0.2, gt=0, description="O2 at the oxygenated surface, mM (air-saturated medium ≈ 0.2)")
    diffusivity_m2s: float = Field(default=2e-9, gt=0, description="O2 diffusivity in tissue/medium, m²/s (standard ≈ 2e-9)")


class O2NecroticParams(BaseModel):
    diameter_um: float = Field(gt=0, description="Spheroid diameter in µm")
    penetration_um: float = Field(gt=0, description="O2 penetration depth in µm (see o2_penetration_depth)")


class O2SupplyDemandParams(BaseModel):
    flow_rate_uLmin: float = Field(gt=0, description="Perfusion flow rate, µL/min")
    total_cells: float = Field(gt=0, description="Total cells in the perfused culture")
    per_cell_fmol_s: float = Field(
        gt=0,
        description="O2 consumption per cell, fmol/s (hepatocytes ≈ 0.007-0.08; "
        "see cell_physiology for the registry OCR range, /60 to convert nmol/min/10⁶ → fmol/s)",
    )
    o2_in_mM: float = Field(default=0.2, gt=0, description="Inlet dissolved O2, mM (air-saturated medium ≈ 0.2)")


class O2PecletParams(BaseModel):
    velocity_mms: float = Field(ge=0, description="Mean flow velocity, mm/s")
    length_mm: float = Field(gt=0, description="Channel length, mm")
    diffusivity_m2s: float = Field(default=2e-9, gt=0, description="O2 diffusivity, m²/s")


class O2DamkohlerParams(BaseModel):
    volumetric_consumption_mol_m3s: float = Field(gt=0, description="Volumetric O2 consumption, mol/m³/s")
    length_mm: float = Field(gt=0, description="Channel length, mm")
    velocity_mms: float = Field(gt=0, description="Mean flow velocity, mm/s")
    inlet_o2_mM: float = Field(default=0.2, gt=0, description="Inlet O2 concentration, mM")


class O2Po2ConversionParams(BaseModel):
    po2_mmHg: float | None = Field(default=None, ge=0, description="O2 partial pressure, mmHg (room air ≈ 150-160)")
    conc_mM: float | None = Field(default=None, ge=0, description="Dissolved O2 concentration, mM")


class TeerFromResistanceParams(BaseModel):
    resistance_total_ohm: float = Field(gt=0, description="Measured total resistance across the insert, Ω")
    resistance_blank_ohm: float = Field(gt=0, description="Cell-free (blank) insert resistance — electrode/medium contribution, Ω")
    area_cm2: float = Field(gt=0, description="Membrane growth area, cm² (24-well ≈ 0.33, 12-well ≈ 1.12)")


class TransendothelialResistanceParams(BaseModel):
    teer_ohm_cm2: float = Field(gt=0, description="Target area-normalised TEER, Ω·cm² (see cell_physiology for the cell's model range)")
    area_cm2: float = Field(gt=0, description="Membrane growth area, cm²")


class PappFromFluxParams(BaseModel):
    flux_nmol_min: float = Field(ge=0, description="Steady-state probe flux across the monolayer, nmol/min")
    area_cm2: float = Field(gt=0, description="Membrane growth area, cm²")
    donor_conc_um: float = Field(gt=0, description="Donor-chamber probe concentration, µM")


class FluxFromPappParams(BaseModel):
    papp_cm_s: float = Field(ge=0, description="Apparent permeability, cm/s (tight barrier ≈ 1e-7-1e-6)")
    donor_conc_um: float = Field(gt=0, description="Donor-chamber probe concentration, µM")
    area_cm2: float = Field(gt=0, description="Membrane growth area, cm²")


class ClearanceParams(BaseModel):
    papp_cm_s: float = Field(ge=0, description="Apparent permeability, cm/s")
    area_cm2: float = Field(gt=0, description="Membrane growth area, cm²")


class EffectivePermeabilityParams(BaseModel):
    diffusivity_m2s: float = Field(gt=0, description="Solute diffusivity in the membrane, m²/s (small molecules in water ≈ 1e-9; in PDMS ≈ 1e-12-1e-10)")
    thickness_um: float = Field(gt=0, description="Membrane thickness, µm")


class ExtractionRatioParams(BaseModel):
    inlet_concentration_uM: float = Field(gt=0, description="Drug concentration in the perfusate entering the chip, µM")
    outlet_concentration_uM: float = Field(ge=0, description="Drug concentration leaving the chip, µM")


class PkClearanceParams(BaseModel):
    inlet_concentration_uM: float = Field(gt=0, description="Inlet drug concentration, µM")
    outlet_concentration_uM: float = Field(ge=0, description="Outlet drug concentration, µM")
    flow_rate_uLmin: float = Field(gt=0, description="Perfusion flow rate, µL/min")


class HalfLifeParams(BaseModel):
    system_volume_uL: float = Field(gt=0, description="Recirculating medium volume (reservoir + chip + tubing), µL")
    clearance_uLmin: float = Field(gt=0, description="Clearance, µL/min (from clearance_uLmin)")


class AccumulationRatioParams(BaseModel):
    half_life_h: float = Field(gt=0, description="Elimination half-life, h")
    dose_interval_h: float = Field(gt=0, description="Time between doses, h")


class MassClearedParams(BaseModel):
    clearance_uLmin: float = Field(gt=0, description="Clearance, µL/min (from clearance_uLmin)")
    inlet_concentration_uM: float = Field(gt=0, description="Inlet drug concentration, µM")
    molecular_weight_g_mol: float = Field(gt=0, description="Drug molecular weight, g/mol")


class ExtrusionVolumeParams(BaseModel):
    travel_distance_um: float = Field(gt=0, description="G-code path length in µm (a 10 mm move = 10000)")
    nozzle_diameter_um: float = Field(gt=0, description="Nozzle inner diameter in µm (e.g. cryo nozzle 500, UV nozzle 300)")


class PathLengthParams(BaseModel):
    dx_um: float = Field(description="Cartesian x offset in µm (can be negative)")
    dy_um: float = Field(description="Cartesian y offset in µm (can be negative)")
    dz_um: float = Field(default=0.0, description="Cartesian z offset in µm (can be negative)")


class BioprintPrintTimeParams(BaseModel):
    travel_distance_um: float = Field(gt=0, description="G-code path length in µm (a 10 mm move = 10000)")
    feed_rate_mm_min: float = Field(gt=0, description="Print feed rate in mm/min")


class BioprintLinesParams(BaseModel):
    footprint_width_um: float = Field(gt=0, description="Width to fill with parallel lines in µm")
    line_pitch_um: float = Field(gt=0, description="Centre-to-centre line pitch in µm")


class CoculturePerWellParams(BaseModel):
    total_density_cells_cm2: float = Field(gt=0, description="Total seeding density across both populations in cells/cm^2")
    area_cm2: float = Field(gt=0, description="Culture surface area per well in cm^2 (96-well ≈ 0.32)")
    fraction_a: float = Field(gt=0, lt=1, description="Fraction of the total assigned to population A")


class CocultureRatioParams(BaseModel):
    count_a: float = Field(ge=0, description="Population A cells")
    count_b: float = Field(gt=0, description="Population B cells")


class EnzymeActivityParams(BaseModel):
    km: float = Field(gt=0, description="Michaelis constant Km, same unit as [S] (µM)")
    s_conc: float = Field(gt=0, description="Substrate concentration [S] in the mix (µM)")
    ki: float = Field(gt=0, description="Inhibitor dissociation constant Ki (µM)")
    i_conc: float = Field(ge=0, description="Inhibitor concentration [I] in the mix (µM)")


class EnzymeIc50Params(BaseModel):
    km: float = Field(gt=0, description="Michaelis constant Km (µM)")
    s_conc: float = Field(gt=0, description="Substrate concentration [S] (µM)")
    ki: float = Field(gt=0, description="Inhibitor Ki (µM)")


class EnzymeApparentKmParams(BaseModel):
    km: float = Field(gt=0, description="Michaelis constant Km (µM)")
    i_conc: float = Field(ge=0, description="Inhibitor concentration [I] (µM)")
    ki: float = Field(gt=0, description="Inhibitor Ki (µM)")


class EnzymeMolarRatioParams(BaseModel):
    amount_a: float = Field(ge=0, description="Moles/amount of component A")
    amount_b: float = Field(gt=0, description="Moles/amount of component B")


class ChampChipsParams(BaseModel):
    n_samples: int = Field(ge=1, description="Cohort size (samples)")
    platform: str = Field(description="BeadChip platform: '450k' (12/chip) or 'epic' (8/chip)")


class ChampFailParams(BaseModel):
    n_arrays: int = Field(ge=1, description="Number of arrays")
    fail_rate: float = Field(ge=0, le=1, description="Expected QC fail rate as a fraction (5% = 0.05)")


class PlinkBedParams(BaseModel):
    n_samples: int = Field(ge=1, description="Genotyped sample count")
    n_variants: int = Field(ge=1, description="Variant count")


class PlinkPerChrParams(BaseModel):
    n_samples: int = Field(ge=1, description="Genotyped sample count")
    n_variants_chr: int = Field(ge=1, description="Variant count on one chromosome")


class SolventEvapParams(BaseModel):
    drop_volume_ul: float = Field(gt=0, description="Drop volume in µL")
    row: str = Field(description="96-well row (A–H)")
    col: int = Field(ge=1, le=12, description="96-well column (1–12)")
    temp_c: float = Field(default=25.0, ge=0, le=50, description="Ambient temperature in °C")
    rh: float = Field(default=0.6, ge=0, le=1, description="Relative humidity as a fraction (0–1)")
    edge_factor: float = Field(default=1.5, ge=1.4, le=2.0, description="Plate-edge evaporation factor (documented range 1.4–2.0)")


class SolventResidualParams(BaseModel):
    drop_volume_ul: float = Field(gt=0, description="Initial drop volume in µL")
    hours: float = Field(ge=0, description="Elapsed evaporation time in h")
    temp_c: float = Field(default=25.0, ge=0, le=50, description="Ambient temperature in °C")
    rh: float = Field(default=0.6, ge=0, le=1, description="Relative humidity as a fraction (0–1)")
    evaporation_factor: float = Field(default=1.0, gt=0, description="Per-well rate multiplier (e.g. plate edge factor)")


class SolventEdgeFactorParams(BaseModel):
    row: str = Field(description="96-well row (A–H)")
    col: int = Field(ge=1, le=12, description="96-well column (1–12)")
    edge_factor: float = Field(default=1.5, ge=1.4, le=2.0, description="Plate-edge evaporation factor (documented range 1.4–2.0)")


# ---------------------------------------------------------------------------
# Tool declarations
# ---------------------------------------------------------------------------

register_tool(
    ShearStressParams,
    "wall_shear_stress",
    "Wall shear stress on cells in a wide rectangular microchannel: tau = 6·mu·Q/(w·h^2). "
    "Call whenever the experiment must match a physiological shear range, or to compute shear "
    "from an intended flow rate.",
    mf.wall_shear_stress,
    "microfluidics",
    units_out="Pa",
)

register_tool(
    FlowForShearParams,
    "flow_rate_for_shear_stress",
    "Inverse calculation: what volumetric flow rate (µL/min) achieves a target wall shear stress "
    "in a given rectangular channel. Use to set a syringe-pump flow from a physiological shear target.",
    mf.flow_rate_for_shear_stress,
    "microfluidics",
    units_out="µL/min",
)

register_tool(
    ReynoldsParams,
    "reynolds_number",
    "Reynolds number in a rectangular channel; sanity check that flow is laminar (microfluidics: << 2300).",
    mf.reynolds_number,
    "microfluidics",
    units_out="dimensionless",
)

register_tool(
    PressureDropParams,
    "pressure_drop",
    "Laminar pressure drop along a rectangular channel, dP = 12·mu·Q·L/(w·h^3). Check the pump can "
    "supply the needed pressure, or estimate pressure-driven flow in a gravity setup.",
    mf.pressure_drop,
    "microfluidics",
    units_out="Pa",
)

register_tool(
    ResidenceTimeParams,
    "residence_time",
    "Mean fluid residence time in the channel (volume / flow). Relevant for dosing and medium-exchange "
    "frequency in perfused culture.",
    mf.residence_time,
    "microfluidics",
    units_out="s",
)

register_tool(
    O2DeliveryParams,
    "o2_delivery_rate",
    "Oxygen delivery rate to cells by perfusion, n_dot = Q·(C_in - C_out). First-order check that "
    "perfusion meets cell O2 demand (air-equilibrated medium ≈ 0.2 mM O2).",
    mf.o2_delivery_rate,
    "microfluidics",
    units_out="µmol/min",
)

register_tool(
    SeedCountParams,
    "seeding_cell_count",
    "Cells to seed onto a culture area at a given density: N = density × area. Plan chip seeding.",
    cell.seeding_cell_count,
    "cell",
    units_out="cells",
)

register_tool(
    GrowthParams,
    "cell_count_after_time",
    "Exponential growth prediction N(t) = N0·2^(t/td). Estimate cell numbers at harvest time.",
    cell.cell_count_after_time,
    "cell",
    units_out="cells",
)

register_tool(
    ConfluenceTimeParams,
    "time_to_confluence",
    "Hours until culture reaches a target confluent cell count, given seeding count and doubling time.",
    cell.time_to_confluence,
    "cell",
    units_out="h",
)

register_tool(
    PlateCellPerWellParams,
    "cells_per_well",
    "Cells to seed per well on a standard multi-well plate at a given density: N = density × well area. "
    "Plan plate-based seeding (6/12/24/48/96-well).",
    culture.cells_per_well,
    "cell",
    units_out="cells/well",
)

register_tool(
    PlateMediumVolumeParams,
    "medium_volume_per_well",
    "Standard working medium volume for one well of a multi-well plate (Corning/Falcon recommended "
    "volume), or area × a custom mL/cm^2 override for low-volume protocols.",
    culture.medium_volume_per_well,
    "cell",
    units_out="mL",
)

register_tool(
    HemocytometerParams,
    "hemocytometer_count",
    "Cell concentration from a hemocytometer: mean cells per corner square × dilution × 1e4 (each "
    "square holds 0.1 µL). Use when a protocol states a hemocytometer or Neubauer count.",
    culture.hemocytometer_count,
    "cell",
    units_out="cells/mL",
)

register_tool(
    TrypanViabilityParams,
    "trypan_blue_viability",
    "Viability percent from a trypan-blue live/dead count: live/(live+dead) × 100. Use when a thawed "
    "or passaged suspension is checked before plating.",
    culture.trypan_blue_viability,
    "cell",
    units_out="%",
)

register_tool(
    ConfluenceToCellsParams,
    "confluence_to_cell_count",
    "Cell count implied by a target confluence: (pct/100) × confluent density × area. Convert a "
    "percent-confluence harvest goal into the cell number it requires.",
    culture.confluence_to_cell_count,
    "cell",
    units_out="cells",
)

register_tool(
    CellsToConfluenceParams,
    "cell_count_to_confluence",
    "Confluence percent implied by a cell count: N/(confluent density × area) × 100. Predict whether "
    "a culture will be over-confluent at harvest.",
    culture.cell_count_to_confluence,
    "cell",
    units_out="%",
)

register_tool(
    PassageSplitParams,
    "passage_split_ratio",
    "Split ratio (fold) when passaging a harvested culture onto a plate at a reseeding density. "
    "Use to plan subculture from a counted harvest.",
    culture.passage_split_ratio,
    "cell",
    units_out="fold",
)

register_tool(
    MoiVirusParams,
    "moi_virus_volume",
    "Virus stock volume for a target multiplicity of infection: MOI × cells / titer. Plan "
    "transduction / infection volumes from a stated MOI.",
    culture.moi_virus_volume,
    "cell",
    units_out="mL",
)

register_tool(
    MolarityParams,
    "molarity_from_mass",
    "Molar concentration from dissolving a weighed mass: C = m/(MW·V). Prepare a compound stock.",
    dosing.molarity_from_mass,
    "dosing",
    units_out="mM",
)

register_tool(
    DilutionParams,
    "dilution_volume",
    "Volume of a more-concentrated stock to add to reach a target working concentration (C1·V1 = C2·V2).",
    dosing.dilution_volume,
    "dosing",
    units_out="mL",
)

register_tool(
    DmsoParams,
    "dmso_fraction",
    "Volume fraction of DMSO in the final medium at a working dose (stock in DMSO / working conc). "
    "Flag if above ~0.1-0.5% v/v (solvent toxicity).",
    dosing.dmso_fraction,
    "dosing",
    units_out="v/v fraction",
)

register_tool(
    SampleSizeParams,
    "sample_size_per_group",
    "Biological replicates per group for a two-sample t-test to detect a given effect at target power. "
    "Call for every controlled comparison; underpowered designs are the top cause of non-reproducible results.",
    stats.sample_size_per_group,
    "stats",
    units_out="n per group",
)

register_tool(
    ReplicatesParams,
    "technical_replicates",
    "Technical replicates per condition to bound the relative standard error of the mean (assay precision).",
    stats.technical_replicates,
    "stats",
    units_out="n",
)

register_tool(
    VerifyProtocolParams,
    "verify_published_protocol",
    "Sanity-check a *published* protocol: recompute the derived numbers (shear, Reynolds, pressure drop, "
    "residence time, channel volume, velocity) from the geometry and flow a paper reports, and flag any "
    "claimed value that does not follow from the paper's own inputs. Use before copying a chip design "
    "or a reported shear/flow pair from the literature.",
    verify_published_protocol,
    "published",
    units_out="verdict per field",
)

register_tool(
    SpheroidVolumeParams,
    "spheroid_volume",
    "Volume of a solid spheroid from its diameter: V = 4/3·π·(d/2)³. Convert a target spheroid size "
    "into the culture volume it represents, or cross-check a reported spheroid volume.",
    spheroid.spheroid_volume_ul,
    "3d_culture",
    units_out="µL",
)

register_tool(
    SpheroidDiameterFromCellsParams,
    "spheroid_diameter_from_cells",
    "Spheroid diameter implied by a cell count: cells packed into a sphere, each of the given mean "
    "cell diameter, at the given packing_fraction (default 1.0 = solid-sphere packing; "
    "1000 cells of 20 µm → ~200 µm at 1.0, ~222 µm at the realistic 0.74).",
    spheroid.spheroid_diameter_from_cells,
    "3d_culture",
    units_out="µm",
)

register_tool(
    CellsPerSpheroidParams,
    "cells_per_spheroid_for_diameter",
    "Cells needed to reach a target spheroid diameter: spheroid volume × packing_fraction ÷ "
    "single-cell volume. Plan seeding for a desired spheroid size; keep spheroids ≤ ~200 µm to "
    "avoid necrotic cores. Lower packing_fraction (real aggregates ≈ 0.65-0.75) needs fewer cells.",
    spheroid.cells_per_spheroid_for_diameter,
    "3d_culture",
    units_out="cells/spheroid",
)

register_tool(
    MediumPerSpheroidParams,
    "medium_volume_per_spheroid",
    "Standard working medium volume for one spheroid in the common vessels: 96-ULA ≈ 100 µL, "
    "384-ULA ≈ 50 µL, hanging drop ≈ 20 µL (one spheroid per well/drop).",
    spheroid.medium_volume_per_spheroid,
    "3d_culture",
    units_out="µL/spheroid",
)

register_tool(
    SpheroidCountParams,
    "spheroids_from_suspension",
    "How many spheroids a counted cell suspension can form at a given cells-per-spheroid: total cells ÷ "
    "cells per spheroid (floored). Plan the number of wells/drops a harvest can seed.",
    spheroid.spheroid_count_from_suspension,
    "3d_culture",
    units_out="spheroids",
)


def _cell_physiology(cell_type: str) -> dict[str, Any]:
    """Look up a cell type's reference physiology from the registry."""
    from labwright.physiology import lookup_cell

    prof = lookup_cell(cell_type)
    if prof is None:
        return {
            "cell_type": cell_type,
            "resolved": None,
            "message": "no profile in the physiology registry — treat physiological targets as unverified",
        }
    return {
        "cell_type": cell_type,
        "resolved": prof.key,
        "organ": prof.organ,
        "barrier": prof.barrier,
        "human_primary": prof.human_primary,
        "animal_derived": prof.animal_derived,
        "bsl": prof.bsl,
        "bsl_hint": prof.bsl_hint,
        "cell_diameter_um": prof.cell_diameter_um,
        "doubling_time_h": list(prof.doubling_time_h) if prof.doubling_time_h else None,
        "doubling_note": prof.doubling_note,
        "seeding_density_cells_cm2": list(prof.seeding_density_cells_cm2)
        if prof.seeding_density_cells_cm2
        else None,
        "shear_range_pa": list(prof.shear_range_pa) if prof.shear_range_pa else None,
        "o2_consumption_nmol_min_1e6": list(prof.o2_consumption_nmol_min_1e6)
        if prof.o2_consumption_nmol_min_1e6
        else None,
        "teer_ohm_cm2": list(prof.teer_ohm_cm2) if prof.teer_ohm_cm2 else None,
        "teer_physiological_ohm_cm2": list(prof.teer_physiological_ohm_cm2)
        if prof.teer_physiological_ohm_cm2
        else None,
        "notes": prof.notes,
        "sources": list(prof.sources),
    }


register_tool(
    CellPhysiologyParams,
    "cell_physiology",
    "Reference physiology of a cell type/line, from the physiology registry: organ, BSL, mean cell "
    "diameter, doubling time, seeding density, physiological shear range, oxygen consumption, and "
    "(for barrier lines) TEER. Call before choosing a physiological target so the design matches a "
    "defensible range instead of a guessed one. Ranges are literature-based with sources.",
    _cell_physiology,
    "physiology",
)


def _o2_po2_conversion(po2_mmHg: float | None = None, conc_mM: float | None = None) -> dict[str, Any]:
    """Bidirectional Henry's-law O2 conversion (give exactly one input)."""
    from labwright.calc import o2 as o2c

    if (po2_mmHg is None) == (conc_mM is None):
        return {"error": "pass exactly one of po2_mmHg or conc_mM"}
    if po2_mmHg is not None:
        conc = o2c.o2_conc_mm_from_po2(po2_mmHg)
        return {"po2_mmHg": po2_mmHg, "conc_mM": round(conc, 4)}
    po2 = o2c.o2_po2_mmhg_from_conc(conc_mM)
    return {"conc_mM": conc_mM, "po2_mmHg": round(po2, 1)}


register_tool(
    O2PenetrationParams,
    "o2_penetration_depth",
    "Krogh O2 penetration depth into a consuming tissue layer: sqrt(2·D·C₀/q). The thickness O2 "
    "diffusing from a surface can still oxygenate; beyond it the tissue is anoxic. Answer 'how "
    "thick can my cell layer be before it suffocates?'. Typical dense tissue: ~10-100 µm.",
    o2.o2_penetration_depth_um,
    "o2",
    units_out="µm",
)

register_tool(
    O2NecroticParams,
    "spheroid_necrotic_fraction",
    "Anoxic (necrotic-core) volume fraction of a spheroid given its diameter and the O2 "
    "penetration depth: (1 - δ/R)³. 0 when fully oxygenated. Check whether a planned spheroid "
    "size will develop a dead core before committing to it.",
    o2.spheroid_necrotic_fraction,
    "o2",
    units_out="volume fraction",
)

register_tool(
    O2SupplyDemandParams,
    "o2_supply_vs_demand",
    "Compare perfused O2 supply (flow × inlet O2, maximal extraction) with cellular demand "
    "(cells × per-cell OCR). Returns supply/demand in µmol/min and hypoxic=True when supply < "
    "demand. Call to check whether a perfused design starves its cells. Use cell_physiology for "
    "the OCR range (÷60 to get fmol/s/cell).",
    o2.o2_supply_vs_demand,
    "o2",
)

register_tool(
    O2PecletParams,
    "o2_peclet",
    "Péclet number for O2 along the channel: u·L/D. ≪1 diffusion dominates (well mixed); ≫1 "
    "flow sweeps O2 past before it diffuses to the cells — a boundary-layer barrier.",
    o2.peclet_number,
    "o2",
    units_out="dimensionless",
)

register_tool(
    O2DamkohlerParams,
    "o2_damkohler",
    "Damköhler I for O2: q·L/(u·C₀). >1 means cells consume O2 faster than flow supplies it — "
    "the outlet is depleted and downstream cells are hypoxic. Call to check longitudinal O2 "
    "depletion in a perfused channel.",
    o2.damkohler_number,
    "o2",
    units_out="dimensionless",
)

register_tool(
    O2Po2ConversionParams,
    "o2_po2_conversion",
    "Henry's-law conversion between dissolved O2 concentration (mM) and partial pressure (mmHg) "
    "at 37 °C. Air-equilibrated medium ≈ 0.2 mM ≈ 150 mmHg. Give exactly one of the two.",
    _o2_po2_conversion,
    "o2",
)

register_tool(
    TeerFromResistanceParams,
    "teer_from_resistance",
    "TEER from raw insert resistance readings: (R_total − R_blank) × area. Area-normalised "
    "resistance is what the literature reports — never quote a bare ohm reading as a TEER. "
    "Call before accepting a barrier readout or planning a transport study; compare against "
    "cell_physiology's model TEER range for the line.",
    barrier.teer_ohm_cm2,
    "barrier",
    units_out="Ω·cm²",
)

register_tool(
    TransendothelialResistanceParams,
    "transendothelial_resistance",
    "Raw insert resistance a target TEER should read at: TEER / area. Inverse of "
    "teer_from_resistance — use to pre-check whether the planned R_total is even in the "
    "instrument's range.",
    barrier.transendothelial_resistance_ohm,
    "barrier",
    units_out="Ω",
)

register_tool(
    PappFromFluxParams,
    "papp_from_flux",
    "Apparent permeability Papp from a steady-state flux measurement: (flux/60)/(area × donor "
    "concentration). cm/s. Tight barriers ≈ 1e-7-1e-6 cm/s; leaky monolayers push to 1e-5. "
    "Call to convert raw transport data into the comparable permeability number.",
    barrier.papp_cm_s,
    "barrier",
    units_out="cm/s",
)

register_tool(
    FluxFromPappParams,
    "flux_from_papp",
    "Steady-state flux a target Papp implies: Papp × C₀ × area × 60. nmol/min. Use to check "
    "the measurement is feasible — low-Papp probes across small inserts produce pmol/min "
    "fluxes that a plate reader may not resolve.",
    barrier.flux_nmol_min,
    "barrier",
    units_out="nmol/min",
)

register_tool(
    ClearanceParams,
    "clearance_from_papp",
    "Permeability-surface-area product (clearance): Papp × area, mL/min. A flow-like number "
    "that is easier to reason about than bare Papp when comparing inserts.",
    barrier.clearance_mL_min,
    "barrier",
    units_out="mL/min",
)

register_tool(
    EffectivePermeabilityParams,
    "effective_permeability",
    "Effective Fick permeability of a passive membrane: D/L, cm/s. A purely diffusive "
    "reference — compare a monolayer's Papp against it to tell diffusion-limited from "
    "barrier-limited transport.",
    barrier.effective_permeability_cm_s,
    "barrier",
    units_out="cm/s",
)

register_tool(
    ExtractionRatioParams,
    "extraction_ratio",
    "First-pass extraction ratio of a perfused chip: E = 1 − C_out/C_in, the fraction of "
    "drug removed from the perfusate in one pass. The core ADME readout of a perfused "
    "organ-on-chip. Call when an experiment compares drug handling across devices/conditions.",
    pk.extraction_ratio,
    "pk",
    units_out="dimensionless",
)

register_tool(
    PkClearanceParams,
    "clearance_uLmin",
    "Volume of perfusate fully cleared of drug per minute: Cl = E·Q. Compare across "
    "devices or against a cell-free control to isolate cell-mediated clearance from "
    "tubing/PDMS binding.",
    pk.clearance_uLmin,
    "pk",
    units_out="µL/min",
)

register_tool(
    HalfLifeParams,
    "half_life_h",
    "Elimination half-life in a recirculating system: t½ = ln2·V/Cl. Assumes a well-mixed "
    "single compartment (reservoir + chip + tubing). Call when the study reports a "
    "half-life or designs a repeat-dosing schedule.",
    pk.half_life_h,
    "pk",
    units_out="h",
)

register_tool(
    AccumulationRatioParams,
    "accumulation_ratio",
    "Steady-state accumulation factor for fixed-interval dosing: R = 1/(1 − e^(−ln2·τ/t½)). "
    "R ≈ 1 = no accumulation (interval ≫ half-life); R grows as the interval drops toward "
    "or below the half-life. Call to predict whether a repeat-dose protocol builds up drug.",
    pk.accumulation_ratio,
    "pk",
    units_out="dimensionless",
)

register_tool(
    MassClearedParams,
    "mass_cleared_ug_h",
    "Absolute mass of drug the chip clears per hour: M = Cl·C_in·MW·6e-5, µg/h. Convert "
    "the volume-based clearance into the mass a bioanalysis lab measures (LC-MS/MS). Call "
    "when the readout is a cleared amount, not a fraction.",
    pk.mass_cleared_ug_h,
    "pk",
    units_out="µg/h",
)

# --- LabMath-Bench domains: micro-extrusion bioprinting (L1) -----------------

register_tool(
    ExtrusionVolumeParams,
    "bioprinting_extrusion_volume_nl",
    "Ink volume deposited over a straight G-code path through a given nozzle: V = π(d/2)²·L, nL. "
    "Call whenever a printing move's deposited ink (or a G-code offset's volume) must be sized.",
    bioprinting.extrusion_volume_nl,
    "bioprinting",
    units_out="nL",
)

register_tool(
    PathLengthParams,
    "bioprinting_path_length",
    "Cartesian length of a G-code coordinate offset (µm): L = √(Δx² + Δy² + Δz²). Call when a "
    "printing move is given as an (x, y, z) offset and the extruded volume needs the true path length.",
    bioprinting.path_length_from_offset,
    "bioprinting",
    units_out="µm",
)

register_tool(
    BioprintPrintTimeParams,
    "bioprinting_print_time",
    "Time to traverse a G-code path at a feed rate: t = L/v, s. Call to check a print segment's duration.",
    bioprinting.print_time_s,
    "bioprinting",
    units_out="s",
)

register_tool(
    BioprintLinesParams,
    "bioprinting_lines_to_cover",
    "Parallel fill lines to cover a footprint at a line pitch: n = ⌈width/pitch⌉. Call to plan a "
    "fill/hatch pattern for a printing region.",
    bioprinting.lines_to_cover,
    "bioprinting",
    units_out="lines",
)

# --- LabMath-Bench domains: co-culture stoichiometry (L2) --------------------

register_tool(
    CoculturePerWellParams,
    "coculture_cells_per_well",
    "Per-well seeding counts of both populations from a total density, area and A-fraction: "
    "N_A = f·ρ·A, N_B = (1−f)·ρ·A. Call when a mixed seeding (e.g. HUVEC-T1 : HepG2 liver-lobule "
    "model) must be budgeted per well.",
    coculture.cells_per_well,
    "coculture",
    units_out="cells/well",
)

register_tool(
    CocultureRatioParams,
    "coculture_seeding_ratio",
    "A : B seeding ratio: r = N_A / N_B. Call to report or compare co-culture stoichiometry.",
    coculture.seeding_ratio,
    "coculture",
    units_out="dimensionless",
)

# --- LabMath-Bench domains: enzyme competitive binding (L2) ------------------

register_tool(
    EnzymeActivityParams,
    "enzyme_fractional_activity",
    "Fraction of the uninhibited rate remaining under competitive inhibition: "
    "v_i/v_0 = [S]/(Km(1+[I]/Ki)+[S]). Call when a competing small molecule (e.g. OA) must be "
    "quantified against a substrate-cofactor reaction (e.g. UDPGA conjugation).",
    enzyme.fractional_activity,
    "enzyme",
    units_out="dimensionless",
)

register_tool(
    EnzymeIc50Params,
    "enzyme_ic50_from_ki",
    "Run-condition IC50 from Ki at a given substrate level (Cheng–Prusoff): IC50 = Ki(1+[S]/Km). "
    "Call to turn an intrinsic Ki into the concentration that halves activity in this mix.",
    enzyme.ic50_from_ki,
    "enzyme",
    units_out="µM",
)

register_tool(
    EnzymeApparentKmParams,
    "enzyme_apparent_km",
    "Apparent Km under competitive inhibition: Km^app = Km(1 + [I]/Ki). Call when a Lineweaver-Burk "
    "or Hanes readout (apparent Km) must be predicted from the mix.",
    enzyme.apparent_km_um,
    "enzyme",
    units_out="µM",
)

register_tool(
    EnzymeMolarRatioParams,
    "enzyme_molar_ratio",
    "Stoichiometric ratio of two components in a reaction mix: A/B. Call for molar ratios like "
    "inhibitor : substrate ([I]/[S]).",
    enzyme.molar_ratio,
    "enzyme",
    units_out="dimensionless",
)

# --- LabMath-Bench domains: pipeline parameterization (L3) -------------------

register_tool(
    ChampChipsParams,
    "champ_chips_for_samples",
    "Physical BeadChips a cohort needs: n_chips = ⌈n_samples / capacity⌉ (450k=12, EPIC=8 per chip). "
    "Call when sizing a ChAMP methylation batch.",
    bioinformatics.champ_chips_for_samples,
    "bioinformatics",
    units_out="chips",
)

register_tool(
    ChampFailParams,
    "champ_expected_failed_arrays",
    "Expected arrays failing a QC gate at a given fail rate: n_fail = n_arrays × p. Call when a "
    "methylation cohort's QC attrition must be budgeted.",
    bioinformatics.champ_expected_failed_arrays,
    "bioinformatics",
    units_out="arrays",
)

register_tool(
    PlinkBedParams,
    "plink_bed_size_mb",
    "Size of a PLINK binary .bed dataset: B = n_samples·n_variants / 4 / 1e6, MB (2 bits/sample/variant). "
    "Call when a genotype dataset's disk/time budget must be sized.",
    bioinformatics.plink_bed_size_mb,
    "bioinformatics",
    units_out="MB",
)

register_tool(
    PlinkPerChrParams,
    "plink_per_chr_bed_size_mb",
    "Size of one chromosome's .bed given its variant count (same 2-bits rule). Call when per-chromosome "
    "jobs are sized from a split.",
    bioinformatics.plink_per_chr_bed_size_mb,
    "bioinformatics",
    units_out="MB",
)

# --- LabMath-Bench domains: solvent evaporation (L3) -------------------------

register_tool(
    SolventEvapParams,
    "solvent_evaporation_rate",
    "Per-well effective evaporation rate (µL/hr): interior Langmuir rate × plate edge factor. Call when "
    "an evaporation gradient across a plate or a hanging-drop budget must be quantified.",
    solvent.effective_evaporation_rate_ul_hr,
    "solvent",
    units_out="µL/hr",
)

register_tool(
    SolventResidualParams,
    "solvent_drop_volume_after_time",
    "Remaining drop volume after a time at stated T/RH (d²-law): V(t) = (V₀^(2/3) − c·f·t)^(3/2), µL. "
    "Call to project when a hanging/sitting drop dries out or its residual volume.",
    solvent.drop_volume_after_time,
    "solvent",
    units_out="µL",
)

register_tool(
    SolventEdgeFactorParams,
    "solvent_edge_well_factor",
    "Evaporation multiplier for a 96-well position (edge wells rows A/H, cols 1/12 ≈ 1.5×, else 1.0×). "
    "Call when a peripheral-well evaporation bias must be applied or explained.",
    solvent.edge_well_factor,
    "solvent",
    units_out="dimensionless",
)


def list_tools() -> list[Tool]:
    """All registered tools, grouped by category."""
    return sorted(REGISTRY.values(), key=lambda t: (t.category, t.name))


def tools_for_llm() -> list[dict[str, Any]]:
    """Registry serialized for the LLM function-calling API."""
    return [t.schema for t in list_tools()]


__all__ = ["Tool", "REGISTRY", "register_tool", "list_tools", "tools_for_llm"]
